import os
import copy
import numpy as np
import scipy as sci
import matplotlib
import matplotlib.pyplot as plt

# Filtering and interpolation of time series movement signal generated by joint keypoints found through MeTRABS
# Experiment with different filters to remove noise and jittering -> moving average, moving MAD + median, lowpass butterworth, etc.
# Experiment with different interpolation methods to fill missing keypoints -> spline, cubic, linear

# The idea is to have multiple different pipelines for groups of joints to account for variations in movements across different parts of the body
# group 1 - head, spine 1, neck (upper body)
# group 2 - hips, spines 2 + 3 (lower body)
# group 3 - shoulders, elbow (upper arms)
# group 4 - wrists, hands (lower arms)

matplotlib.use('TkAgg')

# Load joint names and edges 
joint_names = np.loadtxt("/mnt/c/metrabs joint connections/joint_names_2.txt", dtype='str')
joint_edges = np.loadtxt("/mnt/c/metrabs joint connections/joint_edges.txt", dtype='int')

# Helper/Select Functions
def find_missing_segments_indices(data):
    # input is assumed to be 1d (corresponding to each joint signal in one direction)
    indices = np.argwhere(np.isnan(data)).flatten()
    
    if len(indices) == 0:
        return []
    
    if len(indices) == 1:
        return [indices]

    segments = []
    
    start_index = indices[0]
    end_index = indices[1]
    
    current_index = start_index
    
    for i, index in enumerate(indices[1:]):
        next_index = index

        if (next_index - current_index) == 1:
            # next_index is part of the same segment 
            current_index = next_index
        else:
            # segment is found, where next_index is the first index of a new segment
            end_index = current_index
            segment = np.arange(start_index, end_index + 1)
            segments.append(segment)
            start_index = next_index
            current_index = next_index
    
    # save the last segment
    segments.append(np.arange(start_index, current_index + 1))
    return segments

def select_joint_group():
    # Prompt user for index of the desired joint signal to analyze (0-24)
    # Returns list of indices for selected joint group
    joint_groups = {1: [3, 12, 15], 2: [1, 2, 6, 9], 
                    3: [16, 17, 18, 19], 4: [20, 21, 22, 23]}
    
    for k, v in joint_groups.items():
        print(f"  {k}: joints {v}")
    try:
        idx = int(input("Enter Joint Group ID (1-4): ").strip())
        if idx not in joint_groups:
            raise ValueError()
    except Exception:
        print("Invalid choice. Defaulting to group 1.")
        idx = 1
        
    return joint_groups[idx]

def replace_missing(data):
    # Replace missing values with NaN
    data_copy = copy.deepcopy(np.array(data, dtype='float'))
    data_copy[data_copy == 0] = np.nan
    contains_nan = np.isnan(data_copy).any()
    return data_copy, contains_nan

# Filtering Functions
def butterworth_filter(data, order, cutoff, sample_freq):
    # Lowpass Butterworth filter 
    data_copy = copy.deepcopy(np.array(data, dtype=float))
    if np.isnan(data_copy).any():
        data_copy = np.nan_to_num(data_copy, nan=0)
        
    [b , a] = sci.signal.butter(order, cutoff, btype='lowpass', analog=False, fs=sample_freq)
    filtered_data = sci.signal.filtfilt(b, a, data_copy)
    
    return filtered_data

def movmad_filter(data, window):
    # Median filter with window 
    data_copy = copy.deepcopy(data)
    if window % 2 == 0:
        window += 1  # to make window odd before passing through filter 
        
    filtered_data = sci.signal.medfilt(data_copy, kernel_size=window)
    
    return filtered_data

def movavg_filter(data, window):
    if window < 1:
        return data
    
    data_copy = copy.deepcopy(data)
    kernel = np.ones(window) / float(window)
    return np.convolve(data_copy, kernel, mode='same')
    
# Interpolation Functions 
def spline_interp(data):
    # Cubic spline interpolation
    data_copy = copy.deepcopy(data)
    nan_index = np.where(np.isnan(data_copy))
    filled_index = np.where(~np.isnan(data_copy))[0]
    filled_data = data_copy[filled_index]
    
    print(len(filled_index))
    print(len(filled_data))
    
    interp_f = sci.interpolate.interp1d(filled_index, filled_data, kind='cubic', bounds_error=False, fill_value=(np.min(filled_data), np.max(filled_data)))
    data_copy[nan_index] = interp_f(nan_index)
    
    return data_copy
  
def segmented_spline_interp(data, known_data, known_index, nan_index):
    # segmented cubic spline interpolation
    data_copy = copy.deepcopy(data)
    interp_f = sci.interpolate.CubicSpline(known_index, known_data)
    data_copy[nan_index] = interp_f(nan_index) # nan_index is assumed to be one segment of missing data 
    
    return data_copy

def linear_interp(data, nan_index=None):
    # Linear interpolation
    # nan_index is a list of lists that contain gaps (indices of continous missing data)
    data_copy = copy.deepcopy(data)
    if nan_index is None:
        nan_index = np.where(np.isnan(data_copy))
    else: 
        nan_index = np.array(nan_index)
    filled_index = np.where(~np.isnan(data_copy))[0]
    filled_data = data_copy[filled_index]
    
    print(len(filled_index))
    print(len(filled_data))
    
    interp_f = sci.interpolate.interp1d(filled_index, filled_data, kind='linear', bounds_error=False, fill_value='extrapolate')
    data_copy[nan_index] = interp_f(nan_index)
    
    return data_copy

def lin_interp_threshold(data, threshold):
    # performs linear interpolation if the number of frames in the gap is equal to smaller than the threshold
    original_signal = copy.deepcopy(data)
    missing_gaps = find_missing_segments_indices(original_signal)
    valid_gaps = [gap for gap in missing_gaps if len(gap) <= threshold]
    
    if valid_gaps == []:
        return original_signal
    
    valid_gaps_list = [index for gap in valid_gaps for index in gap]
    interp_signal = linear_interp(original_signal, valid_gaps_list)
    
    return interp_signal
            

# Plotting Function
def plot_movement(raw_data, filtered_data, start, end, sample_freq, person_label):
    # Skeletal Visualization (Original vs Filtered and/or Interpolated data)
    # Plots the skeleton based on the original and filtered or interpolated signals, returns 0 if successful, returns -1 if an error arises 
    # raw_data and filtered_data must contain all keypoints to be plotted
    raw_data_np = np.array(raw_data)
    filtered_data_np = np.array(filtered_data)
    
    # Check if time interval makes sense (start time must be greater than end time (in frames))
    if start <= end:
        print("Invalid time interval.")
        return -1
    
    if raw_data_np.shape() != filtered_data_np.shape():
        print("Raw and filtered datasets are not the same size.")
        return -1
    
    joint_count = raw_data_np.shape(0)
    if joint_count != 24:
        print("Partial skeletal detection.")
        return -1
        
    # Converts frame into timestamps for x-axis (time axis)  
    interval = np.arange(start, end)
    period = 1/sample_freq
    
    # Figure w/ 2 subplots, original skeleton (left), filtered skeleton (right)
    # Figure w/ 1 plot, both skeleton placed one after the other
    
    fig, img_ax = plt.subplots(1, 2)
    fig.suptitle(f'Original vs Filtered Skeleton - {person_label}')
    img_ax[0].set_title('Before Filtering')
    img_ax[1].set_title('After Filtering')
    
    for a in img_ax:
        a.set_xlabel('X-Coordinate')
        a.set_ylabel('Y-Coordinate')
        a.invert_yaxis()
    
    for frame in interval:
        img_ax[0].scatter(raw_data_np[:, 0, frame], raw_data_np[:, 1, frame], s=2, color='blue')
        img_ax[1].scatter(filtered_data_np[:, 0, frame], filtered_data_np[:, 1, frame], s=2, color='red')
        
        for i_start, i_end in joint_edges:
            raw_joint_x = [raw_data_np[i_start, 0, frame], raw_data_np[i_end, 0, frame]]
            raw_joint_y = [raw_data_np[i_start, 1, frame], raw_data_np[i_end, 1, frame]]
            filtered_joint_x = [filtered_data_np[i_start, 0, frame], filtered_data_np[i_end, 0, frame]]
            filtered_joint_y = [filtered_data_np[i_start, 1, frame], filtered_data_np[i_end, 1, frame]]
            
            img_ax[0].plot(raw_joint_x, raw_joint_y, linestyle='solid', color='blue', marker='o', markersize=4)
            img_ax[1].plot(filtered_joint_x, filtered_joint_y, linestyle='solid', color='red', marker= 'o', markersize=4)
            
        fig.tight_layout()
        plt.show()
        plt.pause(period)
        plt.close(fig)
        
    return 0

def main():
    
    keypoints_dir = "/mnt/c/3HYPER FREEPLAY DV METRABS/MATLAB Keypoints 2/2D Keypoints"
    fs = 30 # Sampling frequency

    # Define labels for plotting signal
    x_label = "Frames"
    y_label = "Coordinate Value"
    
    # Define filter parameters (2 for butterworth, 1 for moving filters)
    order = 2
    cutoff_freq = 9
    window = 40
    
    for keypoints in sorted(os.listdir(keypoints_dir)):
        # Load keypoints
        keypoints_path = os.path.join(keypoints_dir, keypoints)
        keypoints_mat = sci.io.loadmat(keypoints_path)
        
        print(f"Opening ... {keypoints_path}")

        # Separate by PID
        person_0_2d = keypoints_mat['person_0_2d']
        person_1_2d = keypoints_mat['person_1_2d']

        # Divide into x, y components
        person_0_2d_x, person_0_2d_y = person_0_2d[:, 0, :], person_0_2d[:, 1, :]
        person_1_2d_x, person_1_2d_y = person_1_2d[:, 0, :], person_1_2d[:, 1, :]

        raw_movement_signals = [person_0_2d_x, person_0_2d_y, person_1_2d_x, person_1_2d_y]
        person_labels = ["person_0_x", "person_0_y", "person_1_x", "person_1_y"]
        
        # Select joint number
        joint_group = select_joint_group()
        
        # Replace missing values with NaN
        raw_movement_signals = [replace_missing(sig) for sig in raw_movement_signals]

        # Select filter and interpolation methods 
        print("Interpolation: Enter 0")
        print("Filtering: Enter 1")

        filter_interp_select = int(input("Select for interpolation or filtering: "))

        # Filtering
        if filter_interp_select == 1:
            for person_label, signal in zip(person_labels, raw_movement_signals):
                for joint in joint_group:
                    joint_data = signal[joint, :]
                    max_frames = len(joint_data)
                    timestamps = np.arange(max_frames) / fs

                    # Skip if all NaN
                    if np.all(np.isnan(joint_data)):
                        print(f"Joint {joint}: all NaN — skipping.")
                        continue

                    # Filtered versions
                    filtered_butter = butterworth_filter(joint_data, order, cutoff_freq, fs)
                    filtered_movavg = movavg_filter(joint_data, window)
                    filtered_movmad = movmad_filter(joint_data, window)

                    # Create a new figure for this joint
                    fig, ax = plt.subplots(3, 1, figsize=(10, 8), sharex=True)
                    fig.suptitle(f'{person_label} - Joint {joint}: Original vs Filtered (fs={fs}Hz, fc={cutoff_freq}Hz, window = {window})')

                    ax[0].plot(timestamps, joint_data, color='gray')
                    ax[0].plot(timestamps, filtered_butter, color='b')
                    ax[0].set_title('Butterworth')

                    ax[1].plot(timestamps, joint_data, color='gray')
                    ax[1].plot(timestamps, filtered_movavg, color='b')
                    ax[1].set_title('Moving Avergage')

                    ax[2].plot(timestamps, joint_data, color='gray')
                    ax[2].plot(timestamps, filtered_movmad, color='g')
                    ax[2].set_title('Moving Median')
                    
                    fig.legend()

                    for a in ax:
                        a.set_ylabel('Coordinate Value')
                    ax[-1].set_xlabel('Time (s)')

                    plt.tight_layout(rect=[0, 0, 1, 0.96])
                    plt.show(block=False)

        # Intepolation
        elif filter_interp_select == 0:
            for person_label, signal in zip(person_labels, raw_movement_signals):
                for joint in joint_group:
                    joint_data = signal[joint, :]
                    max_frames = len(joint_data)
                    timestamps = np.arange(max_frames) / fs

                    if np.all(np.isnan(joint_data)):
                        print(f"Joint {joint}: all NaN — skipping.")
                        continue

                    # Interpolate
                    interp_linear = linear_interp(joint_data)
                    interp_spline = spline_interp(joint_data)

                    # Plot per joint
                    fig, ax = plt.subplots(3, 1, figsize=(10, 6), sharex=True)
                    fig.suptitle(f'{person_label} - Joint {joint}: Original vs Interpolated')

                    ax[0].plot(timestamps, joint_data, color='gray')
                    ax[0].set_title('Original')

                    ax[1].plot(timestamps, interp_linear, color='b')
                    ax[1].set_title('Linear Interpolation')

                    ax[2].plot(timestamps, interp_spline, color='r')
                    ax[2].set_title('Cubic Spline Interpolation')

                    for a in ax:
                        a.set_ylabel('Coordinate Value')
                    ax[-1].set_xlabel('Time (s)')

                    plt.tight_layout()
                    plt.show(block=False)

        else:
            print("Invalid selection.")

        
if __name__ == "__main__":
    main()
    
    
    
